const scriptAssetMaps = {
  unit01: {
    '1_Einhard_Lupus.jpg': '/images/scripts/unit01/1-einhard-lupus.jpg',
    '1_Feliciano.jpg': '/images/scripts/unit01/1-feliciano.jpg',
    '1_Saint_Gall_Vergil.jpg': '/images/scripts/unit01/1-saint-gall-vergil.jpg',
    '1_Square_Capitals.jpeg': '/images/scripts/unit01/1-square-capitals.jpeg',
    'Pacioli.jpg': '/images/scripts/unit01/pacioli.jpg',
    'Trajanic inscription.jpg': '/images/scripts/unit01/trajanic-inscription.jpg',
  },
  unit02: {
    '2 Os Compared.jpg': '/images/scripts/unit02/2-os-compared.jpg',
    '2_Gallus_Cropped.jpg': '/images/scripts/unit02/2-gallus-cropped.jpg',
    '2_Rustic_Cap.jpeg': '/images/scripts/unit02/2-rustic-cap.jpeg',
    '2_Rustic_Utrecht_Psalter.jpg': '/images/scripts/unit02/2-rustic-utrecht-psalter.jpg',
    '4_Rustic_Vatican_Vergil.jpg': '/images/scripts/unit02/4-rustic-vatican-vergil.jpg',
    'Hawara_Papyrus_24.jpg': '/images/scripts/unit02/hawara-papyrus-24.jpg',
  },
  unit03: {
    '3_Butini_Papyrus.jpg': '/images/scripts/unit03/3-butini-papyrus.jpg',
    '3_ORC_Deed_of_slave_sale.jpg': '/images/scripts/unit03/3-orc-deed-of-slave-sale.jpg',
    '3_Ravenna Papyrus 1.jpg': '/images/scripts/unit03/3-ravenna-papyrus-1.jpg',
    'Litterae caelestes.jpg': '/images/scripts/unit03/litterae-caelestes.jpg',
    'NRC Vitalis.jpg': '/images/scripts/unit03/nrc-vitalis.jpg',
  },
  unit04: {
    '4_Claromontanus.JPEG': '/images/scripts/unit04/4-claromontanus.jpeg',
    '4_Half-Uncial, Formula Fabiana.png': '/images/scripts/unit04/4-half-uncial-formula-fabiana.png',
    '4_Uncial_Vercellensis.gif': '/images/scripts/unit04/4-uncial-vercellensis.gif',
    '4_half-uncial_hilary.jpg': '/images/scripts/unit04/4-half-uncial-hilary.jpg',
    '4_uncial_fuldensis_2.jpg': '/images/scripts/unit04/4-uncial-fuldensis-2.jpg',
    'B-R Uncial, Justinian Code.jpg': '/images/scripts/unit04/b-r-uncial-justinian-code.jpg',
    'De bellis macedonicis a.jpg': '/images/scripts/unit04/de-bellis-macedonicis-a.jpg',
    'De bellis macedonicis b.jpg': '/images/scripts/unit04/de-bellis-macedonicis-b.jpg',
    'Uncial.jpeg': '/images/scripts/unit04/uncial.jpeg',
    'half uncial.jpeg': '/images/scripts/unit04/half-uncial.jpeg',
  },
  unit05: {
    '5_Book_of_Dimma.jpg': '/images/scripts/unit05/5-book-of-dimma.jpg',
    '5_Insular_Kells.jpg': '/images/scripts/unit05/5-insular-kells.jpg',
    '5_Insular_majuscule.jpeg': '/images/scripts/unit05/5-insular-majuscule.jpeg',
  },
  unit06: {
    '6_Alemannic.jpg': '/images/scripts/unit06/6-alemannic.jpg',
    '6_Cassiodorus_eN.JPEG': '/images/scripts/unit06/6-cassiodorus-en.jpeg',
    '6_Chelles.jpg': '/images/scripts/unit06/6-chelles.jpg',
    '6_Luxeuil.jpeg': '/images/scripts/unit06/6-luxeuil.jpeg',
    '6_Rhaetian.jpg': '/images/scripts/unit06/6-rhaetian.jpg',
    '6_Winithar.jpg': '/images/scripts/unit06/6-winithar.jpg',
  },
  unit07: {
    '7_1_Moralia-in-Job.jpg': '/images/scripts/unit07/7-1-moralia-in-job.jpg',
    '7_2 Etymologies.jpg': '/images/scripts/unit07/7-2-etymologies.jpg',
    '7_3_Etymologies_BNE Digital, 10008-1.jpg': '/images/scripts/unit07/7-3-etymologies-bne-digital-10008-1.jpg',
    '7_4_Etymologies_BNE Digital, 10008-2.jpg': '/images/scripts/unit07/7-4-etymologies-bne-digital-10008-2.jpg',
    'visigothic.jpeg': '/images/scripts/unit07/visigothic.jpeg',
  },
  unit08: {
    '8_Beneventan_mature.jpg': '/images/scripts/unit08/8-beneventan-mature.jpg',
    '8_Early_Beneventan_Cropped.jpg': '/images/scripts/unit08/8-early-beneventan-cropped.jpg',
    'beneventan.jpeg': '/images/scripts/unit08/beneventan.jpeg',
    'beneventan_ligature.jpeg': '/images/scripts/unit08/beneventan-ligature.jpeg',
  },
  unit09: {
    '9_Augustine_owned_by_Petrarch.JPEG': '/images/scripts/unit09/9-augustine-owned-by-petrarch.jpeg',
    '9_First_Caroline.jpg': '/images/scripts/unit09/9-first-caroline.jpg',
    '9_Godescalc.JPEG': '/images/scripts/unit09/9-godescalc.jpeg',
    '9_Half_uncial_toward_minuscule.jpg': '/images/scripts/unit09/9-half-uncial-toward-minuscule.jpg',
    '9_Maurdramnus.JPEG': '/images/scripts/unit09/9-maurdramnus.jpeg',
    '9_Pregothic_Vergil.jpg': '/images/scripts/unit09/9-pregothic-vergil.jpg',
    '9_Tours_Bible_1.jpg': '/images/scripts/unit09/9-tours-bible-1.jpg',
    '9_Tours_Bible_2.jpg': '/images/scripts/unit09/9-tours-bible-2.jpg',
  },
  unit10: {
    '10 Citeaux.jpg': '/images/scripts/unit10/10-citeaux.jpg',
    '10_Bock_Writing_Manual.jpg': '/images/scripts/unit10/10-bock-writing-manual.jpg',
    '10_GothicTextualis.jpeg': '/images/scripts/unit10/10-gothictextualis.jpeg',
    '10_Göttingen_Gutenberg.jpg': '/images/scripts/unit10/10-gottingen-gutenberg.jpg',
    '10_Hagen_Scribe_Advertisement.jpg': '/images/scripts/unit10/10-hagen-scribe-advertisement.jpg',
    '10_Pepys_Alphabet.jpg': '/images/scripts/unit10/10-pepys-alphabet.jpg',
    '10_Protogothic.jpeg': '/images/scripts/unit10/10-protogothic.jpeg',
    '10_Quadrata_Renaud.jpeg': '/images/scripts/unit10/10-quadrata-renaud.jpeg',
    '10_Rotunda.jpeg': '/images/scripts/unit10/10-rotunda.jpeg',
  },
  unit11: {
    '11_Antiquior.jpg': '/images/scripts/unit11/11-antiquior.jpg',
    '11_Bastarda.jpg': '/images/scripts/unit11/11-bastarda.jpg',
    '11_Batarde.jpeg': '/images/scripts/unit11/11-batarde.jpeg',
    '11_Paradiso.jpg': '/images/scripts/unit11/11-paradiso.jpg',
    '11_Secretary.jpg': '/images/scripts/unit11/11-secretary.jpg',
  },
  unit12: {
    '12_1_Poggio_Cicero.jpg': '/images/scripts/unit12/12-1-poggio-cicero.jpg',
    '12_2_Poggio_Valerius.jpg': '/images/scripts/unit12/12-2-poggio-valerius.jpg',
    '12_3_Poggio.jpg': '/images/scripts/unit12/12-3-poggio.jpg',
    '12_4.jpg': '/images/scripts/unit12/12-4.jpg',
    '12_5.png': '/images/scripts/unit12/12-5.png',
    '12_6.jpg': '/images/scripts/unit12/12-6.jpg',
    '12_7.jpg': '/images/scripts/unit12/12-7.jpg',
    '12_8.jpg': '/images/scripts/unit12/12-8.jpg',
    '12_9_a.jpeg': '/images/scripts/unit12/12-9-a.jpeg',
    '12_9_b.jpeg': '/images/scripts/unit12/12-9-b.jpeg',
  },
}

function createUnit({
  unit,
  numeral,
  slug,
  title,
  dates,
  sourceFile,
}) {
  return {
    unit,
    numeral,
    slug,
    title,
    dates,
    sourceFile,
    sourcePath: `/source/scripts/unit${String(unit).padStart(2, '0')}.html`,
    assetMap: scriptAssetMaps[`unit${String(unit).padStart(2, '0')}`] ?? {},
  }
}

export const scriptsOverview = {
  eyebrow: 'Tutorials',
  title: 'Medieval Palaeography',
  subtitle: 'A Tutorial in Twelve Units',
  lede:
    'This tutorial introduces the principal scripts of the Latin West from Roman antiquity through the early modern period. Each unit surveys a script family or historical phase — its origins, characteristic letter forms, regional variants, and surviving examples. The units are designed to be read in sequence, since later scripts are best understood against the background of earlier ones, but each unit can also stand independently as a reference.',
  sourceFiles: [
    'Palaeography Tutorial/Palaeography Tutorials/index.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit01_Square.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit02_Rustic.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit03_Roman_Cursives.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit04_Uncial_and_Half-Uncial.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit05_Insular.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit06_Merovingian_Pre-Caroline.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit07_Visigothic.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit08_Beneventan.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit09_Caroline_Pre-Gothic.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit10_Textualis.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit11_Gothic_Cursive.html',
    'Palaeography Tutorial/Palaeography Tutorials/unit12_Humanist.html',
  ],
}

export const scriptUnits = [
  createUnit({
    unit: 1,
    numeral: 'I',
    slug: 'origins-square-capitals',
    title: 'The Origins of the Alphabet, Inscriptions, and Square Capitals',
    dates: '8th cent. BCE – 15th cent. CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit01_Square.html',
  }),
  createUnit({
    unit: 2,
    numeral: 'II',
    slug: 'rustic-book-capitals',
    title: 'Rustic Book Capitals',
    dates: '1st cent. BCE – 9th cent. CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit02_Rustic.html',
  }),
  createUnit({
    unit: 3,
    numeral: 'III',
    slug: 'roman-cursive',
    title: 'Old and New Roman Cursive',
    dates: '3rd cent. BCE – 7th cent. CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit03_Roman_Cursives.html',
  }),
  createUnit({
    unit: 4,
    numeral: 'IV',
    slug: 'uncial-half-uncial',
    title: 'Uncial and Half-Uncial',
    dates: 'c. 100 – c. 800 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit04_Uncial_and_Half-Uncial.html',
  }),
  createUnit({
    unit: 5,
    numeral: 'V',
    slug: 'insular',
    title: 'Insular Scripts',
    dates: 'c. 600 – c. 1200 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit05_Insular.html',
  }),
  createUnit({
    unit: 6,
    numeral: 'VI',
    slug: 'merovingian-precaroline',
    title: 'Merovingian and Precaroline Minuscule',
    dates: 'c. 520 – c. 840 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit06_Merovingian_Pre-Caroline.html',
  }),
  createUnit({
    unit: 7,
    numeral: 'VII',
    slug: 'visigothic',
    title: 'Visigothic',
    dates: 'c. 700 – c. 1200 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit07_Visigothic.html',
  }),
  createUnit({
    unit: 8,
    numeral: 'VIII',
    slug: 'beneventan',
    title: 'Beneventan',
    dates: 'c. 780 – c. 1300 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit08_Beneventan.html',
  }),
  createUnit({
    unit: 9,
    numeral: 'IX',
    slug: 'caroline-pregothic',
    title: 'Caroline and Pregothic Minuscule',
    dates: 'c. 760 – c. 1200 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit09_Caroline_Pre-Gothic.html',
  }),
  createUnit({
    unit: 10,
    numeral: 'X',
    slug: 'gothic-textualis',
    title: 'Gothic Textualis',
    dates: 'c. 1100 – c. 1500 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit10_Textualis.html',
  }),
  createUnit({
    unit: 11,
    numeral: 'XI',
    slug: 'gothic-cursive',
    title: 'Gothic Cursive Hands',
    dates: 'c. 1200 – c. 1500 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit11_Gothic_Cursive.html',
  }),
  createUnit({
    unit: 12,
    numeral: 'XII',
    slug: 'humanist-scripts',
    title: 'Humanist Scripts',
    dates: 'c. 1375 – c. 1550 CE',
    sourceFile: 'Palaeography Tutorial/Palaeography Tutorials/unit12_Humanist.html',
  }),
]


export function getScriptUnit(slug) {
  return scriptUnits.find((unit) => unit.slug === slug)
}
