export const scriptsOverview = {
  eyebrow: 'Tutorials',
  title: 'Scripts',
  lede:
    'This tutorial introduces the principal scripts of the Latin West from Roman antiquity through the early modern period.',
  introduction: [
    'Each unit surveys a script family or historical phase, its origins, characteristic letter forms, regional variants, and surviving examples.',
    'The finished HTML package says that the units are designed to be read in sequence, since later scripts are best understood against the background of earlier ones, but each unit can also stand independently as a reference.',
  ],
  sourceFiles: ['Tutorials/4. Scripts/html/index.html', 'Tutorials/4. Scripts/html/unit01.html through unit12.html'],
  ductusNote:
    'The ductus gallery acts as a visual practice companion to the main units, letting you compare stroke construction across major script families.',
}

export const scriptUnits = [
  {
    unit: 1,
    numeral: 'I',
    slug: 'origins-square-capitals',
    title: 'The Origins of the Alphabet, Inscriptions, and Square Capitals',
    dates: '8th cent. BCE - 15th cent. CE',
    sourcePath: '/source/scripts/unit01.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Follow the emergence of the alphabet, Roman inscriptions, and the monumental forms behind square capitals.',
    timelineSlug: 'history-roman-alphabet',
    ductusImage: '/images/ductus/Square_Capitals.png',
    ductusLabel: 'Square Capitals',
  },
  {
    unit: 2,
    numeral: 'II',
    slug: 'rustic-book-capitals',
    title: 'Rustic Book Capitals',
    dates: '1st cent. BCE - 9th cent. CE',
    sourcePath: '/source/scripts/unit02.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Study the narrow, rhythmical capital hand used in late antique and early medieval books.',
    timelineSlug: 'roman-inscriptions',
    ductusImage: '/images/ductus/Rustic_Cap.png',
    ductusLabel: 'Rustic Capitals',
  },
  {
    unit: 3,
    numeral: 'III',
    slug: 'roman-cursive',
    title: 'Old and New Roman Cursive',
    dates: '3rd cent. BCE - 7th cent. CE',
    sourcePath: '/source/scripts/unit03.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Compare the documentary cursive traditions that shaped everyday Roman writing.',
    timelineSlug: 'roman-inscriptions',
    ductusImage: null,
    ductusLabel: null,
  },
  {
    unit: 4,
    numeral: 'IV',
    slug: 'uncial-half-uncial',
    title: 'Uncial and Half-Uncial',
    dates: 'c. 100 - c. 800 CE',
    sourcePath: '/source/scripts/unit04.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Trace the rounded formal scripts that became central to late antique and early medieval books.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/Uncial.png',
    ductusLabel: 'Uncial',
  },
  {
    unit: 5,
    numeral: 'V',
    slug: 'insular',
    title: 'Insular Scripts',
    dates: 'c. 600 - c. 1200 CE',
    sourcePath: '/source/scripts/unit05.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Explore Insular writing across Britain and Ireland, from formal majuscule to learned bookhands.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/Insular majusc.png',
    ductusLabel: 'Insular Majuscule',
  },
  {
    unit: 6,
    numeral: 'VI',
    slug: 'merovingian-precaroline',
    title: 'Merovingian and Precaroline Minuscule',
    dates: 'c. 520 - c. 840 CE',
    sourcePath: '/source/scripts/unit06.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Examine regional scripts before Carolingian reform, including Merovingian traditions.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/Merovingian.png',
    ductusLabel: 'Merovingian',
  },
  {
    unit: 7,
    numeral: 'VII',
    slug: 'visigothic',
    title: 'Visigothic',
    dates: 'c. 700 - c. 1200 CE',
    sourcePath: '/source/scripts/unit07.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Follow the distinctive script culture of the Iberian peninsula and its manuscript forms.',
    timelineSlug: 'monasticism',
    ductusImage: null,
    ductusLabel: null,
  },
  {
    unit: 8,
    numeral: 'VIII',
    slug: 'beneventan',
    title: 'Beneventan',
    dates: 'c. 780 - c. 1300 CE',
    sourcePath: '/source/scripts/unit08.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Situate Beneventan within southern Italy, Montecassino, and regional liturgical culture.',
    timelineSlug: 'montecassino',
    ductusImage: null,
    ductusLabel: null,
  },
  {
    unit: 9,
    numeral: 'IX',
    slug: 'caroline-pregothic',
    title: 'Caroline and Pregothic Minuscule',
    dates: 'c. 760 - c. 1200 CE',
    sourcePath: '/source/scripts/unit09.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Track Carolingian reform and the gradual transition from Caroline to pregothic hands.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/Carolingian.png',
    ductusLabel: 'Carolingian',
  },
  {
    unit: 10,
    numeral: 'X',
    slug: 'gothic-textualis',
    title: 'Gothic Textualis',
    dates: 'c. 1100 - c. 1500 CE',
    sourcePath: '/source/scripts/unit10.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Study the dense formal Gothic bookhand associated with later medieval textual production.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/GothicTextualis.png',
    ductusLabel: 'Gothic Textualis',
  },
  {
    unit: 11,
    numeral: 'XI',
    slug: 'gothic-cursive',
    title: 'Gothic Cursive Hands',
    dates: 'c. 1200 - c. 1500 CE',
    sourcePath: '/source/scripts/unit11.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'Move from formal Gothic writing into faster documentary and literary cursive hands.',
    timelineSlug: 'monasticism',
    ductusImage: '/images/ductus/Batarde.png',
    ductusLabel: 'Batarde',
  },
  {
    unit: 12,
    numeral: 'XII',
    slug: 'humanist-scripts',
    title: 'Humanist Scripts',
    dates: 'c. 1375 - c. 1550 CE',
    sourcePath: '/source/scripts/unit12.html',
    sourceStatus: 'Finished HTML unit',
    sourceNote: 'Lesson content is loaded from the finished Scripts HTML package.',
    summary: 'End with the humanist recovery and reinterpretation of earlier script models.',
    timelineSlug: 'history-roman-alphabet',
    ductusImage: null,
    ductusLabel: null,
  },
]

export const ductusEntries = [
  { slug: 'square-capitals', title: 'Square Capitals', image: '/images/ductus/Square_Capitals.png', relatedUnit: 'origins-square-capitals' },
  { slug: 'rustic-capitals', title: 'Rustic Capitals', image: '/images/ductus/Rustic_Cap.png', relatedUnit: 'rustic-book-capitals' },
  { slug: 'uncial', title: 'Uncial', image: '/images/ductus/Uncial.png', relatedUnit: 'uncial-half-uncial' },
  { slug: 'half-uncial', title: 'Half-Uncial', image: '/images/ductus/half uncial.png', relatedUnit: 'uncial-half-uncial' },
  { slug: 'insular-majuscule', title: 'Insular Majuscule', image: '/images/ductus/Insular majusc.png', relatedUnit: 'insular' },
  { slug: 'merovingian', title: 'Merovingian', image: '/images/ductus/Merovingian.png', relatedUnit: 'merovingian-precaroline' },
  { slug: 'carolingian', title: 'Carolingian', image: '/images/ductus/Carolingian.png', relatedUnit: 'caroline-pregothic' },
  { slug: 'protogothic', title: 'Protogothic', image: '/images/ductus/Protogothic.png', relatedUnit: 'caroline-pregothic' },
  { slug: 'gothic-textualis', title: 'Gothic Textualis', image: '/images/ductus/GothicTextualis.png', relatedUnit: 'gothic-textualis' },
  { slug: 'rotunda', title: 'Rotunda', image: '/images/ductus/Rotunda.png', relatedUnit: 'gothic-textualis' },
  { slug: 'batarde', title: 'Batarde', image: '/images/ductus/Batarde.png', relatedUnit: 'gothic-cursive' },
]

export function getScriptUnit(slug) {
  return scriptUnits.find((unit) => unit.slug === slug)
}
